---
- hosts: all
  gather_facts: True
  environment:
    DURATION: "{{duration}}"
    MC_HOST: "{{mc_host}}"
    SPAWN_X: "{{spawn_x}}"
    SPAWN_Y: "{{spawn_y}}"
    WORKLOAD_VARIANT: "{{workload_variant}}"
  tasks:
    - name: Set game spawn location
      shell:
        cmd: |
          source ~/.bashrc
          node set_spawn.js | tee set_spawn-{{ inventory_hostname }}.log
        chdir: "{{wd}}"
      run_once: true # Only run on one machine
    - name: Run Minecraft bot
      shell:
        cmd: |
          source ~/.bashrc
          nvm use 22
          # nohup node bot.js &> bot-{{ inventory_hostname }}.log &
          node bot.js | tee bot-{{ inventory_hostname }}.log
          echo $! > bot-{{inventory_hostname}}.pid
        chdir: "{{wd}}"
      environment:
        BOT_INDEX: "{{ groups['all'].index(inventory_hostname) }}"
