---
- name: Clean Telegraf files but keep metrics and logs
  gather_facts: false
  hosts: all
  tasks:
    - name: Check telegraf working directory
      stat:
        path: "{{ wd | default('.') }}"
      register: telegraf_wd
      failed_when: false

    - name: Find items to remove (everything except metrics CSVs and telegraf logs)
      shell: |
        find "{{wd}}" -mindepth 1 -maxdepth 1 \
          ! -name "metrics-*.csv" \
          ! -name "telegraf.log" \
          ! -name "telegraf*.pid" \
          -print
      register: telegraf_cleanup_paths
      changed_when: false
      failed_when: false
      when: telegraf_wd.stat.exists | default(false)

    - name: Remove Telegraf artifacts
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ telegraf_cleanup_paths.stdout_lines | default([]) }}"
      when: telegraf_wd.stat.exists | default(false)

    - name: Remove Telegraf PID files
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ lookup('ansible.builtin.fileglob', wd + '/telegraf-*.pid', wantlist=True) }}"
      when: telegraf_wd.stat.exists | default(false)
